### ISSUE TITLE
Design game state and store an instance of it server side

### ISSUE THREAD

**Issue by deejai** [sankeatan/elementum#1]

**Comment by sankeatan** [comment]
We decided to store this outside the server and client, right?

**Comment by deejai** [comment]
yeah in a new folder meant to share code with both client and server

**Comment by sankeatan** [comment]
<img width="286" alt="Screen Shot 2022-07-18 at 12 18 59 PM" src="https://user-images.githubusercontent.com/47090053/179556760-2b169dd2-d988-4431-867c-03d4136ee3bf.png">
<img width="382" alt="Screen Shot 2022-07-18 at 12 18 42 PM" src="https://user-images.githubusercontent.com/47090053/179556776-3c7c8917-637c-4805-a7eb-5cdcc703b6cf.png">

**Comment by sankeatan** [comment]
Instead of in the shared file?

**Comment by deejai** [comment]
yeah it should be in server/app.js
