### ISSUE TITLE
Create emit() and on() relationships for sending game state from server and player actions from client

### ISSUE THREAD

**Issue by deejai** [sankeatan/elementum#2]

**Comment by sankeatan** [comment]
This is the emitter in app.component.ts
<img width="751" alt="Screen Shot 2022-07-18 at 2 58 11 PM" src="https://user-images.githubusercontent.com/47090053/179583752-7f2e3d88-e06a-4329-bba2-29411494a44b.png">

This is the on in app.js
<img width="736" alt="Screen Shot 2022-07-18 at 2 59 06 PM" src="https://user-images.githubusercontent.com/47090053/179583897-47314400-2309-4e2d-ab84-0fce081dc3fc.png">
